
plugins:
    - vue

extends:
    - airbnb-base
    - "plugin:vue/base"
    - "plugin:vue/vue3-essential"
    - "plugin:vue/vue3-strongly-recommended"
    - "plugin:vue/vue3-recommended"
    - prettier

globals:
    OC: readonly
    t: readonly

rules:
    no-plusplus:
        - error
        - allowForLoopAfterthoughts: true
    quotes:
        - error
        - single
        - avoidEscape: true
    semi:
        - error
        - always
    # disallow certain syntax forms
    # http://eslint.org/docs/rules/no-restricted-syntax
    no-restricted-syntax:
      - error
      - ForInStatement
      - LabeledStatement
      - WithStatement
    # While we are still on Vue2, we need this. Remove once on Vue3
    vue/no-deprecated-dollar-listeners-api: off
    # While we are still on Vue2, we need this. Remove once on Vue3
    vue/no-deprecated-v-bind-sync: off


root: true

settings:
    "import/resolver":
        alias:
            map:
                - ["cookbook", "./src"]
                - ["icons", "./node_modules/vue-material-design-icons"]


overrides:
    - files: [ "src/composables/**/*.js" ]
      rules:
        import/prefer-default-export: off

